### ISSUE TITLE
Best practices TODO

### ISSUE THREAD

**Issue by anandbaburajan** [FOSS-Cell-GECPKD/whitespace-stego#12]
### Code
* [x] Proper readable and maintable code with consistent spacing and indentation
* [x] Functions follow the "Do One Thing" rule (single-responsibility)
* [x] Followed DRY (Don’t Repeat Yourself)
* [x] Added comments wherever required
* [x] Proper naming conventions
* [x] Avoided deep nesting

### Readme
* [x] Badges (similar to the Gitter badge. You can maybe use: https://shields.io/)
* [x] Description (why this project exists)
* [x] Features (working of the project)
* [x] Setup (Quick start instructions with how to download and use your project)
* [x] Contributing.md (How can others contribute?)
* [x] License ("This project is licensed under the <your license>")

### Tests and CI/CD
* [x] Wrote tests
* [x] Deployed the project
* [x] Added CI/CD tools to your project (maybe CircleCI or TravisCI)

**Comment by anandbaburajan** [comment]
@VipinVIP and @alwin48, great work and thanks for contributing! You're just left with one item in your TODO and please check your Gitter too for a previous comment! :D

**Comment by VipinVIP** [comment]
@AnandBaburajan  Thank you for reviewing : .. We will look into the remaining  CI / CD part and complete it as soon as possible.🙌🏽

**Comment by anandbaburajan** [comment]
Closing this issue since @alwin48 & @VipinVIP have completed OpenHack '20 successfully! Congratulations!
